name: "Update helm version"

on: 
  repository_dispatch:
    types: [update-helm]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: update manifest
        run: docker run --rm -v "${PWD}":/workdir mikefarah/yq:3.2.1 yq write --inplace --verbose deploy/helm/${{ github.event.client_payload.path}}/Chart.yaml appVersion 1

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Manifest for ${{ github.event.client_payload.path}} to v${{ github.event.client_payload.tag }}
          tagging_message: 'v${{ github.event.client_payload.tag }}'
          skip_checkout: true
